/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JTextField;
import main.Proyecto;

/**
 *
 * @author victor
 */
public class VentanaPlatos extends javax.swing.JFrame {

    private boolean encontrado;
    /**
     * Creates new form VentanaPlatos
     */
    public VentanaPlatos() {
        initComponents();
        JPanelUnidades.setVisible(false);
        JPanelCambiarNombre.setVisible(false);
        JPanelEliminar.setVisible(false);
        JPanelAñadir.setVisible(false);
        
       
    }
    
    public void mostrarPAñadir() {
        JPanelAñadir.setVisible(true);
        JExiste.setVisible(false);
    }
    
    public void mostrarPModificarUnidades() {
        JPanelUnidades.setVisible(true);
        JActualizado.setVisible(false);
        JActualizado1.setVisible(false);
    }
    public void mostrarPBorrar() {
        JPanelEliminar.setVisible(true);
        JBorrado.setVisible(false);
        
    }
    
    public void mostrarPCambiarNombrePlato() {
        JPanelCambiarNombre.setVisible(true);
        JModificado.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BAtras = new javax.swing.JButton();
        JPanelCambiarNombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfNombreCN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BCambiarNombre = new javax.swing.JButton();
        tfNombreCN1 = new javax.swing.JTextField();
        BValidarCN = new javax.swing.JButton();
        JModificado = new javax.swing.JLabel();
        JPanelUnidades = new javax.swing.JPanel();
        JNombreCU = new javax.swing.JLabel();
        JUnidadesApuntadasCU = new javax.swing.JLabel();
        JUnidadesActualesCU = new javax.swing.JLabel();
        tfNombreCU = new javax.swing.JTextField();
        tfUnidadesActuales = new javax.swing.JTextField();
        tfUnidadesApuntadas = new javax.swing.JTextField();
        BValidarCU = new javax.swing.JButton();
        JActualizado = new javax.swing.JLabel();
        BCambiarUnidades = new javax.swing.JButton();
        JActualizado1 = new javax.swing.JLabel();
        JPanelEliminar = new javax.swing.JPanel();
        JNombreE = new javax.swing.JLabel();
        tfNombreE = new javax.swing.JTextField();
        BEliminarE = new javax.swing.JButton();
        JBorrado = new javax.swing.JLabel();
        JPanelAñadir = new javax.swing.JPanel();
        JNombreA = new javax.swing.JLabel();
        tfNombreA = new javax.swing.JTextField();
        JUnidadesA = new javax.swing.JLabel();
        BAñadir = new javax.swing.JButton();
        tfUnidadesA = new javax.swing.JTextField();
        BValidarA = new javax.swing.JButton();
        JExiste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 370));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 46, 131));
        jLabel1.setText("PLATOS");

        BAtras.setBackground(new java.awt.Color(0, 0, 0));
        BAtras.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        BAtras.setForeground(new java.awt.Color(255, 255, 255));
        BAtras.setText("ATRÁS");
        BAtras.setFocusPainted(false);
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });

        JPanelCambiarNombre.setBackground(new java.awt.Color(255, 255, 255));
        JPanelCambiarNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    CAMBIAR NOMBRE AL PLATO    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelCambiarNombre.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JPanelCambiarNombre.setPreferredSize(new java.awt.Dimension(600, 180));

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre :");

        tfNombreCN.setBackground(new java.awt.Color(255, 255, 255));
        tfNombreCN.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombreCN.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreCN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombreCN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreCNFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre Nuevo: ");

        BCambiarNombre.setBackground(new java.awt.Color(255, 255, 255));
        BCambiarNombre.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BCambiarNombre.setForeground(new java.awt.Color(181, 46, 131));
        BCambiarNombre.setText("CAMBIAR");
        BCambiarNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BCambiarNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BCambiarNombre.setFocusPainted(false);
        BCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCambiarNombreActionPerformed(evt);
            }
        });

        tfNombreCN1.setBackground(new java.awt.Color(255, 255, 255));
        tfNombreCN1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombreCN1.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreCN1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombreCN1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreCN1FocusGained(evt);
            }
        });

        BValidarCN.setBackground(new java.awt.Color(255, 255, 255));
        BValidarCN.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BValidarCN.setForeground(new java.awt.Color(181, 46, 131));
        BValidarCN.setText("VALIDAR");
        BValidarCN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BValidarCN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BValidarCN.setFocusPainted(false);
        BValidarCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValidarCNActionPerformed(evt);
            }
        });

        JModificado.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        JModificado.setForeground(new java.awt.Color(255, 0, 0));
        JModificado.setText("Plato modificado");

        javax.swing.GroupLayout JPanelCambiarNombreLayout = new javax.swing.GroupLayout(JPanelCambiarNombre);
        JPanelCambiarNombre.setLayout(JPanelCambiarNombreLayout);
        JPanelCambiarNombreLayout.setHorizontalGroup(
            JPanelCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCambiarNombreLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(BValidarCN, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addGroup(JPanelCambiarNombreLayout.createSequentialGroup()
                .addGroup(JPanelCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelCambiarNombreLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombreCN1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelCambiarNombreLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(JModificado))
                    .addGroup(JPanelCambiarNombreLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombreCN, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        JPanelCambiarNombreLayout.setVerticalGroup(
            JPanelCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCambiarNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombreCN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreCN1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelCambiarNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BValidarCN, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(BCambiarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JModificado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPanelUnidades.setBackground(new java.awt.Color(255, 255, 255));
        JPanelUnidades.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    CAMBIAR UNIDADES    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelUnidades.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        JNombreCU.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNombreCU.setForeground(new java.awt.Color(0, 0, 0));
        JNombreCU.setText("Nombre :");

        JUnidadesApuntadasCU.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JUnidadesApuntadasCU.setForeground(new java.awt.Color(0, 0, 0));
        JUnidadesApuntadasCU.setText("Unidades Apuntadas:");

        JUnidadesActualesCU.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JUnidadesActualesCU.setForeground(new java.awt.Color(0, 0, 0));
        JUnidadesActualesCU.setText("Unidades Actuales:");

        tfNombreCU.setBackground(new java.awt.Color(255, 255, 255));
        tfNombreCU.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombreCU.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreCU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombreCU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreCUFocusGained(evt);
            }
        });

        tfUnidadesActuales.setBackground(new java.awt.Color(255, 255, 255));
        tfUnidadesActuales.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfUnidadesActuales.setForeground(new java.awt.Color(0, 0, 0));
        tfUnidadesActuales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfUnidadesActuales.setEnabled(false);
        tfUnidadesActuales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUnidadesActualesFocusGained(evt);
            }
        });

        tfUnidadesApuntadas.setBackground(new java.awt.Color(255, 255, 255));
        tfUnidadesApuntadas.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfUnidadesApuntadas.setForeground(new java.awt.Color(0, 0, 0));
        tfUnidadesApuntadas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfUnidadesApuntadas.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfUnidadesApuntadas.setEnabled(false);
        tfUnidadesApuntadas.setFocusable(false);

        BValidarCU.setBackground(new java.awt.Color(255, 255, 255));
        BValidarCU.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BValidarCU.setForeground(new java.awt.Color(181, 46, 131));
        BValidarCU.setText("VALIDAR");
        BValidarCU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BValidarCU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BValidarCU.setFocusPainted(false);
        BValidarCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValidarCUActionPerformed(evt);
            }
        });

        JActualizado.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        JActualizado.setForeground(new java.awt.Color(255, 0, 0));
        JActualizado.setText("Unidades actualizadas");

        BCambiarUnidades.setBackground(new java.awt.Color(255, 255, 255));
        BCambiarUnidades.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BCambiarUnidades.setForeground(new java.awt.Color(181, 46, 131));
        BCambiarUnidades.setText("CAMBIAR");
        BCambiarUnidades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BCambiarUnidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BCambiarUnidades.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BCambiarUnidades.setEnabled(false);
        BCambiarUnidades.setFocusPainted(false);
        BCambiarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCambiarUnidadesActionPerformed(evt);
            }
        });

        JActualizado1.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        JActualizado1.setForeground(new java.awt.Color(255, 0, 0));
        JActualizado1.setText("Unidades de 0-999");

        javax.swing.GroupLayout JPanelUnidadesLayout = new javax.swing.GroupLayout(JPanelUnidades);
        JPanelUnidades.setLayout(JPanelUnidadesLayout);
        JPanelUnidadesLayout.setHorizontalGroup(
            JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(JNombreCU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                .addGroup(JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                        .addComponent(JActualizado)
                        .addGap(42, 42, 42)
                        .addComponent(BValidarCU, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(BCambiarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                        .addComponent(JUnidadesApuntadasCU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUnidadesApuntadas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JUnidadesActualesCU)))
                .addGap(18, 18, 18)
                .addGroup(JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                        .addComponent(tfUnidadesActuales)
                        .addGap(39, 39, 39))
                    .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                        .addComponent(JActualizado1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JPanelUnidadesLayout.setVerticalGroup(
            JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNombreCU)
                    .addComponent(tfNombreCU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JUnidadesApuntadasCU)
                    .addComponent(JUnidadesActualesCU)
                    .addComponent(tfUnidadesActuales, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUnidadesApuntadas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                        .addComponent(JActualizado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanelUnidadesLayout.createSequentialGroup()
                        .addGroup(JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BValidarCU, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BCambiarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JActualizado1))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );

        JPanelEliminar.setBackground(new java.awt.Color(255, 255, 255));
        JPanelEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    ELIMINAR PLATO    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelEliminar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JPanelEliminar.setPreferredSize(new java.awt.Dimension(600, 181));

        JNombreE.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNombreE.setForeground(new java.awt.Color(0, 0, 0));
        JNombreE.setText("Nombre :");

        tfNombreE.setBackground(new java.awt.Color(255, 255, 255));
        tfNombreE.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombreE.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombreE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreEFocusGained(evt);
            }
        });

        BEliminarE.setBackground(new java.awt.Color(255, 255, 255));
        BEliminarE.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BEliminarE.setForeground(new java.awt.Color(181, 46, 131));
        BEliminarE.setText("ELIMINAR");
        BEliminarE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BEliminarE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BEliminarE.setFocusPainted(false);
        BEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarEActionPerformed(evt);
            }
        });

        JBorrado.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        JBorrado.setForeground(new java.awt.Color(255, 0, 0));
        JBorrado.setText("El plato ha sido eliminado");

        javax.swing.GroupLayout JPanelEliminarLayout = new javax.swing.GroupLayout(JPanelEliminar);
        JPanelEliminar.setLayout(JPanelEliminarLayout);
        JPanelEliminarLayout.setHorizontalGroup(
            JPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelEliminarLayout.createSequentialGroup()
                .addGroup(JPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelEliminarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(JNombreE)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelEliminarLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(BEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JBorrado)
                .addGap(169, 169, 169))
        );
        JPanelEliminarLayout.setVerticalGroup(
            JPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelEliminarLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(JBorrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNombreE)
                    .addComponent(tfNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        JPanelAñadir.setBackground(new java.awt.Color(255, 255, 255));
        JPanelAñadir.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    AÑADIR PLATO    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelAñadir.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JPanelAñadir.setPreferredSize(new java.awt.Dimension(600, 183));

        JNombreA.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNombreA.setForeground(new java.awt.Color(0, 0, 0));
        JNombreA.setText("Nombre :");

        tfNombreA.setBackground(new java.awt.Color(255, 255, 255));
        tfNombreA.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombreA.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombreA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreAFocusGained(evt);
            }
        });

        JUnidadesA.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JUnidadesA.setForeground(new java.awt.Color(0, 0, 0));
        JUnidadesA.setText("Unidades :");

        BAñadir.setBackground(new java.awt.Color(255, 255, 255));
        BAñadir.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BAñadir.setForeground(new java.awt.Color(181, 46, 131));
        BAñadir.setText("AÑADIR");
        BAñadir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAñadir.setEnabled(false);
        BAñadir.setFocusPainted(false);
        BAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAñadirActionPerformed(evt);
            }
        });

        tfUnidadesA.setBackground(new java.awt.Color(255, 255, 255));
        tfUnidadesA.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfUnidadesA.setForeground(new java.awt.Color(0, 0, 0));
        tfUnidadesA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfUnidadesA.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfUnidadesA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUnidadesAFocusGained(evt);
            }
        });
        tfUnidadesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUnidadesAActionPerformed(evt);
            }
        });

        BValidarA.setBackground(new java.awt.Color(255, 255, 255));
        BValidarA.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BValidarA.setForeground(new java.awt.Color(181, 46, 131));
        BValidarA.setText("VALIDAR");
        BValidarA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BValidarA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BValidarA.setFocusPainted(false);
        BValidarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValidarAActionPerformed(evt);
            }
        });

        JExiste.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        JExiste.setForeground(new java.awt.Color(255, 0, 0));
        JExiste.setText("El plato ya existe");

        javax.swing.GroupLayout JPanelAñadirLayout = new javax.swing.GroupLayout(JPanelAñadir);
        JPanelAñadir.setLayout(JPanelAñadirLayout);
        JPanelAñadirLayout.setHorizontalGroup(
            JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAñadirLayout.createSequentialGroup()
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelAñadirLayout.createSequentialGroup()
                        .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelAñadirLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(JNombreA)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAñadirLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JUnidadesA)
                                .addGap(12, 12, 12)))
                        .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUnidadesA, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                            .addComponent(tfNombreA)))
                    .addGroup(JPanelAñadirLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(BValidarA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAñadirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JExiste)
                .addGap(232, 232, 232))
        );
        JPanelAñadirLayout.setVerticalGroup(
            JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAñadirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNombreA)
                    .addComponent(tfNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUnidadesA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JUnidadesA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JExiste)
                .addGap(8, 8, 8)
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(BValidarA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JPanelAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JPanelUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPanelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPanelCambiarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(BAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCambiarNombreActionPerformed
        cambiarNombrePlato(tfNombreCN, tfNombreCN1);
    }//GEN-LAST:event_BCambiarNombreActionPerformed

    private void BCambiarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCambiarUnidadesActionPerformed
        cambiarUnidadesPlato(tfNombreCU,tfUnidadesActuales);
    }//GEN-LAST:event_BCambiarUnidadesActionPerformed

    private void BAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAñadirActionPerformed
        
        try {
            int Unidades = Integer.parseInt(tfUnidadesA.getText());
            Proyecto.añadirPlato(tfNombreA.getText(), Unidades);
            tfNombreA.setText("");
            tfUnidadesA.setText("");
            tfNombreA.setForeground(Color.black);
            
        } catch (Exception e) {
            System.out.println("No se ha podido insertar");
        }
    }//GEN-LAST:event_BAñadirActionPerformed

    private void BValidarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValidarAActionPerformed
        try {
            boolean unidadesOK = validarUnidades(tfUnidadesA);
            consultarNombre();
            boolean nombreOK = consultaNombre(tfNombreA);
            
            if(nombreOK==false){
                
                BAñadir.setEnabled(false);
                tfUnidadesA.setForeground(Color.black);
                tfNombreA.setForeground(Color.black);
               // Datos del plato
                String UnidadesPlato = String.valueOf(Proyecto.getUnidadesPlato());
                tfUnidadesA.setText(UnidadesPlato);
            }
            else{
                BAñadir.setEnabled(false);
            }
            
            if(tfUnidadesA.getText().isEmpty()){
                tfUnidadesA.setText("Debes insertar algun valor");
            }
            
            if(!tfUnidadesA.getText().isEmpty() && unidadesOK==true && nombreOK==true){
                BAñadir.setEnabled(true);
            }
            else{
                BAñadir.setEnabled(false);
            }
        
        } catch (Exception e) {
            System.out.println(e.getClass());
        }
        
    }//GEN-LAST:event_BValidarAActionPerformed

    private void tfUnidadesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUnidadesAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUnidadesAActionPerformed

    private void BValidarCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValidarCUActionPerformed
        try {
            boolean consultaNombre = consultaNombre(tfNombreCU);
            if(consultaNombre){
                tfNombreCU.setForeground(Color.red);
                tfNombreCU.setText("No existe");
                tfUnidadesApuntadas.setText("");
            }
            else{
                tfNombreCU.setForeground(Color.green);
                consultarUnidades(tfNombreCU);
                tfUnidadesActuales.setEnabled(true);
                
            }
            
            boolean validarUnidades = validarUnidades(tfUnidadesApuntadas);
            if(!validarUnidades){
                tfUnidadesApuntadas.setForeground(Color.red);
            }
            
            if(!consultaNombre && validarUnidades){
                BCambiarUnidades.setEnabled(true);
                Proyecto.mostrarUnidades(tfNombreCU.getText());
            }
            else{
                BCambiarUnidades.setEnabled(false);
            }
            
            
        } catch (Exception e) {
            System.out.println(e.getClass());
        }
        
    }//GEN-LAST:event_BValidarCUActionPerformed

    private void tfNombreCUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreCUFocusGained
        tfNombreCU.setText("");
        tfNombreCU.setForeground(Color.black);
        JActualizado.setVisible(false);
        BCambiarUnidades.setEnabled(false);
    }//GEN-LAST:event_tfNombreCUFocusGained

    private void BEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarEActionPerformed
        try {
            boolean borrarPlato = Proyecto.borrarPlato(tfNombreE.getText());
            if(borrarPlato)
            {
              tfNombreE.setText("");  
              JBorrado.setVisible(true);
              tfNombreE.setForeground(Color.black);
            }
            else{
                tfNombreE.setText("No encontrado");
                tfNombreE.setForeground(Color.red);
            }

                    
        } catch (Exception e) {
            System.out.println(e.getClass());
        }
    }//GEN-LAST:event_BEliminarEActionPerformed

    private void tfNombreEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreEFocusGained
        tfNombreE.setText("");
        tfNombreE.setForeground(Color.black);
    }//GEN-LAST:event_tfNombreEFocusGained

    private void tfUnidadesAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUnidadesAFocusGained
        tfUnidadesA.setForeground(Color.black);
        tfUnidadesA.setText("");
    }//GEN-LAST:event_tfUnidadesAFocusGained

    private void tfNombreAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreAFocusGained
        BAñadir.setEnabled(false);
        tfNombreA.setForeground(Color.black);
        tfNombreA.setText("");
        tfUnidadesA.setText("");
    }//GEN-LAST:event_tfNombreAFocusGained

    private void BValidarCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValidarCNActionPerformed
        try {
            consultaNombreCambiar(tfNombreCN);
            
            if(tfNombreCN1.getText().isEmpty()){
                tfNombreCN1.setText("Debes escribir un nuevo nombre para el plato");
                tfNombreCN1.setForeground(Color.red);
                BCambiarNombre.setEnabled(false);
            }
            else{
                BCambiarNombre.setEnabled(true);
            }
                      
            
        } catch (Exception e) {
            System.out.println(e.getClass());
        }
    }//GEN-LAST:event_BValidarCNActionPerformed

    private void tfNombreCNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreCNFocusGained
        tfNombreCN.setForeground(Color.black);
        tfNombreCN.setText("");
        BCambiarNombre.setEnabled(false);
        JModificado.setVisible(false);
    }//GEN-LAST:event_tfNombreCNFocusGained

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        Proyecto.cerrarVenatanaPlatos();
    }//GEN-LAST:event_BAtrasActionPerformed

    private void tfUnidadesActualesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUnidadesActualesFocusGained
        tfUnidadesActuales.setText("");
    }//GEN-LAST:event_tfUnidadesActualesFocusGained

    private void tfNombreCN1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreCN1FocusGained
        tfNombreCN1.setForeground(Color.black);
        tfNombreCN1.setText("");
        BCambiarNombre.setEnabled(false);
        JModificado.setVisible(false);
    }//GEN-LAST:event_tfNombreCN1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPlatos().setVisible(true);
            }
        });
    }
    
    private void consultarNombre(){
        try{
          boolean correcto = validarNombre(tfNombreA);
           if (correcto)
           {
               tfNombreA.setForeground(Color.green);
           }
           else
           {
               tfNombreA.setForeground(Color.red);
               BAñadir.setEnabled(false);
           }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       }
    }
    
     private boolean validarNombre(JTextField Nombre) throws Exception{
        String nombrepat = "^[A-zÑñ\\s]{1,30}$";
        if (Pattern.matches(nombrepat, Nombre.getText())== false ){
            return false;
        }
        else{
            return true;
        }
    }
     
      private boolean validarUnidades(JTextField Unidades) throws Exception{
        String unidadespat = "^\\d{1,3}$";
        if (Pattern.matches(unidadespat, Unidades.getText())== false ){
            Unidades.setForeground(Color.red);
            return false;
        }
        else{
            Unidades.setForeground(Color.green);
            return true;
        }
    }
     
     private boolean consultaNombre(JTextField Nombre){
        try{
            
            encontrado = Proyecto.buscarPlatoPorNombre(Nombre.getText());
           if (encontrado)
           {
               // Plato encontrado
               
               return false;
           }
           else
           {
               // Plato nuevo
               return true;
           }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       }
        return true;
    }
       
    private void platoNuevo() throws Exception{
        JExiste.setVisible(false);
        tfUnidadesA.setEnabled(true);
    }
    
    private boolean consultarUnidades(JTextField Nombre){
        try{
            encontrado = Proyecto.buscarPlatoPorNombre(Nombre.getText());
           if (encontrado)
           {
               // Plato encontrado
               String UnidadesPlato = String.valueOf(Proyecto.getUnidadesPlato());
                BCambiarUnidades.setEnabled(true);
                tfNombreCU.setForeground(Color.black);
                 // Datos del plato
                tfUnidadesApuntadas.setText(UnidadesPlato);
               return true;
           }
           else
           {
               // Plato nuevo
               platoNuevo();
               return true;
           }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       }
        return false;
    }
    
    private void cambiarUnidadesPlato(JTextField Nombre, JTextField Unidades){
       boolean cambiarUnidades;
       
        try {
            if(Unidades.getText().isEmpty()){
                JActualizado1.setVisible(true);
            }
            int UnidadesActuales = Integer.parseInt(Unidades.getText());
            if(UnidadesActuales<=999 && UnidadesActuales>0){
                cambiarUnidades = Proyecto.cambiarUnidadesPlato(Nombre.getText(),UnidadesActuales);
                if(cambiarUnidades){
                    JActualizado.setVisible(true);
                    tfNombreCU.setText("");
                    tfNombreCU.setForeground(Color.black);
                    tfUnidadesActuales.setText("");
                    tfUnidadesApuntadas.setText("");
                    tfUnidadesActuales.setEnabled(false);
                    tfUnidadesActuales.setForeground(Color.black);
                    tfUnidadesApuntadas.setForeground(Color.black);
                    JActualizado1.setVisible(false);
                }
                else{
                    JActualizado.setVisible(false);
                    JActualizado1.setVisible(true);
                }
            }
            else{
                JActualizado.setVisible(false);
                JActualizado1.setVisible(true);
            }
            
        } catch (Exception e) {
            System.out.println("No se ha podido insertar" + e.getClass());
        }
    }
    
     private void consultaNombreCambiar(JTextField Nombre){
        try{
            encontrado = Proyecto.buscarPlatoPorNombre(Nombre.getText());
           if (encontrado)
           {
               // Plato encontrado
               tfNombreCN.setForeground(Color.green);
               BCambiarNombre.setEnabled(true);
           }
           else
           {
               // Plato nuevo
               tfNombreCN.setForeground(Color.red);
               tfNombreCN.setText("No existe");
               JModificado.setVisible(false);
               BCambiarNombre.setEnabled(false);
           }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       } 
    }
     private void cambiarNombrePlato(JTextField NombreV, JTextField NombreN){
       boolean modificado;
        try {
            
            modificado = Proyecto.modificarPlato(NombreV.getText(), NombreN.getText());
            if(modificado){
                JModificado.setVisible(true);
                tfNombreCN.setText("");
                tfNombreCN1.setText("");
                tfNombreCN.setForeground(Color.black);
                tfNombreCN1.setForeground(Color.black);
            }
            
            
            
            
            
        } catch (Exception e) {
            System.out.println("No se ha podido insertar" + e.getClass());
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BAñadir;
    private javax.swing.JButton BCambiarNombre;
    private javax.swing.JButton BCambiarUnidades;
    private javax.swing.JButton BEliminarE;
    private javax.swing.JButton BValidarA;
    private javax.swing.JButton BValidarCN;
    private javax.swing.JButton BValidarCU;
    private javax.swing.JLabel JActualizado;
    private javax.swing.JLabel JActualizado1;
    private javax.swing.JLabel JBorrado;
    private javax.swing.JLabel JExiste;
    private javax.swing.JLabel JModificado;
    private javax.swing.JLabel JNombreA;
    private javax.swing.JLabel JNombreCU;
    private javax.swing.JLabel JNombreE;
    private javax.swing.JPanel JPanelAñadir;
    private javax.swing.JPanel JPanelCambiarNombre;
    private javax.swing.JPanel JPanelEliminar;
    private javax.swing.JPanel JPanelUnidades;
    private javax.swing.JLabel JUnidadesA;
    private javax.swing.JLabel JUnidadesActualesCU;
    private javax.swing.JLabel JUnidadesApuntadasCU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfNombreA;
    private javax.swing.JTextField tfNombreCN;
    private javax.swing.JTextField tfNombreCN1;
    private javax.swing.JTextField tfNombreCU;
    private javax.swing.JTextField tfNombreE;
    private javax.swing.JTextField tfUnidadesA;
    private javax.swing.JTextField tfUnidadesActuales;
    private javax.swing.JTextField tfUnidadesApuntadas;
    // End of variables declaration//GEN-END:variables
}
