/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFrame;
import main.Proyecto;

/**
 *
 * @author victor
 */
public class VentanaEstadisticas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEstadisticas
     */
    public VentanaEstadisticas() {
        initComponents();
        JPanelClientes.setVisible(false);
        JPanelPlatos.setVisible(false);
    }
    
    public void mostrarCliente() {
        JPanelClientes.setVisible(true);
        try{
            
            String clientes = Proyecto.rellenarTablaClientes();
            tfClientes.setText(clientes);
            String mediaPedidos = Proyecto.mediaPedidos();
            tfMedia.setText(mediaPedidos);
            String nClientes = Proyecto.contarClientes();
            tfNClientes.setText(nClientes);
        }catch (Exception e) {
            System.out.println("Error a la hora de rellenar las estadisticas de cliente" + e.getClass());
        }
        
    }
    
    public void mostrarPlato() {
        JPanelPlatos.setVisible(true);
        setSize(700, 440);
        try{
            
            String platos = Proyecto.rellenarTablaPlatos();
            tfPlatos.setText(platos);
            String nPlatos = Proyecto.contarPlatos();
            tfNPlatos.setText(nPlatos);
        }catch (Exception e) {
            System.out.println("Error a la hora de rellenar las estadisticas de cliente" + e.getClass());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JPanelClientes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfClientes = new javax.swing.JTextArea();
        tfMedia = new javax.swing.JTextField();
        tfNClientes = new javax.swing.JTextField();
        JPanelPlatos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfPlatos = new javax.swing.JTextArea();
        tfNPlatos = new javax.swing.JTextField();
        BAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 510));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 46, 131));
        jLabel1.setText("ESTADÍSTICAS");

        JPanelClientes.setBackground(new java.awt.Color(255, 255, 255));
        JPanelClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    CLIENTES    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelClientes.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JPanelClientes.setPreferredSize(new java.awt.Dimension(600, 350));

        jLabel2.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("MEDIA DE PEDIDOS:");

        jLabel3.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nº DE CLIENTES:");

        tfClientes.setBackground(new java.awt.Color(255, 255, 255));
        tfClientes.setColumns(20);
        tfClientes.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfClientes.setLineWrap(true);
        tfClientes.setRows(5);
        tfClientes.setToolTipText("");
        tfClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tfClientes.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfClientes.setEnabled(false);
        jScrollPane2.setViewportView(tfClientes);

        tfMedia.setBackground(new java.awt.Color(255, 255, 255));
        tfMedia.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        tfMedia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMedia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tfMedia.setCaretColor(new java.awt.Color(0, 0, 0));
        tfMedia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfMedia.setEnabled(false);
        tfMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMediaActionPerformed(evt);
            }
        });

        tfNClientes.setBackground(new java.awt.Color(255, 255, 255));
        tfNClientes.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        tfNClientes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tfNClientes.setCaretColor(new java.awt.Color(0, 0, 0));
        tfNClientes.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfNClientes.setEnabled(false);
        tfNClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClientesLayout = new javax.swing.GroupLayout(JPanelClientes);
        JPanelClientes.setLayout(JPanelClientesLayout);
        JPanelClientesLayout.setHorizontalGroup(
            JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClientesLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClientesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClientesLayout.createSequentialGroup()
                        .addGroup(JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMedia)
                            .addComponent(tfNClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(156, 156, 156))))
        );
        JPanelClientesLayout.setVerticalGroup(
            JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClientesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanelPlatos.setBackground(new java.awt.Color(255, 255, 255));
        JPanelPlatos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    PLATOS    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelPlatos.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JPanelPlatos.setPreferredSize(new java.awt.Dimension(600, 350));

        jLabel5.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nº DE PLATOS:");

        tfPlatos.setBackground(new java.awt.Color(255, 255, 255));
        tfPlatos.setColumns(20);
        tfPlatos.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfPlatos.setLineWrap(true);
        tfPlatos.setRows(5);
        tfPlatos.setToolTipText("");
        tfPlatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tfPlatos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfPlatos.setEnabled(false);
        jScrollPane3.setViewportView(tfPlatos);

        tfNPlatos.setBackground(new java.awt.Color(255, 255, 255));
        tfNPlatos.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        tfNPlatos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNPlatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tfNPlatos.setCaretColor(new java.awt.Color(0, 0, 0));
        tfNPlatos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfNPlatos.setEnabled(false);
        tfNPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNPlatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelPlatosLayout = new javax.swing.GroupLayout(JPanelPlatos);
        JPanelPlatos.setLayout(JPanelPlatosLayout);
        JPanelPlatosLayout.setHorizontalGroup(
            JPanelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPlatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(tfNPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(JPanelPlatosLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        JPanelPlatosLayout.setVerticalGroup(
            JPanelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPlatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JPanelPlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelPlatosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addGroup(JPanelPlatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BAtras.setBackground(new java.awt.Color(0, 0, 0));
        BAtras.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        BAtras.setForeground(new java.awt.Color(255, 255, 255));
        BAtras.setText("ATRÁS");
        BAtras.setFocusPainted(false);
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPanelPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(BAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        Proyecto.cerrarVentanaEstadisticas();
    }//GEN-LAST:event_BAtrasActionPerformed

    private void tfMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMediaActionPerformed

    private void tfNClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNClientesActionPerformed

    private void tfNPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNPlatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNPlatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstadisticas().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JPanel JPanelClientes;
    private javax.swing.JPanel JPanelPlatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea tfClientes;
    private javax.swing.JTextField tfMedia;
    private javax.swing.JTextField tfNClientes;
    private javax.swing.JTextField tfNPlatos;
    private javax.swing.JTextArea tfPlatos;
    // End of variables declaration//GEN-END:variables
}
