/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JButton;
import main.*;
import javax.swing.JTextField;

/**
 *
 * @author victor
 */
public class VentanaClientes extends javax.swing.JFrame {
    
    private boolean encontrado;
    private int contadorBuscarModificar = 0;
    private int contadorAñadir1 = 0;
    private int contadorAñadir2 = 0;
    private int contadorAñadir3 = 0;
    
   

    /**
     * Creates new form VenatanaCliente
     */
    public VentanaClientes() {
        initComponents();
        
        JExiste.setVisible(false);
        BNuevo.setVisible(false);
        JBorrado.setVisible(false);
        JModificado.setVisible(false);
        JPanelAñadir.setVisible(false);
        JPanelBorrar.setVisible(false);
        JPanelBuscar.setVisible(false);
        JPanelModificar.setVisible(false);
    }
    
    public void mostrarCAñadir() {
        JPanelAñadir.setVisible(true);
    }
    
    public void mostrarCBorrar() {
        JPanelBorrar.setVisible(true);
    }
    
    public void mostrarCBuscar() {
        JPanelBuscar.setVisible(true);
    }
    
    public void mostrarCModificar() {
        JPanelModificar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JPanelAñadir = new javax.swing.JPanel();
        JNombre1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        JDNI1 = new javax.swing.JLabel();
        BAñadir = new javax.swing.JButton();
        tfDNI = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        JTelefono1 = new javax.swing.JLabel();
        JExiste = new javax.swing.JLabel();
        BNuevo = new javax.swing.JButton();
        BValidar1 = new javax.swing.JButton();
        BAtras = new javax.swing.JButton();
        JPanelBorrar = new javax.swing.JPanel();
        JDNI2 = new javax.swing.JLabel();
        tfDNIB = new javax.swing.JTextField();
        BBorrar = new javax.swing.JButton();
        JBorrado = new javax.swing.JLabel();
        BValidar2 = new javax.swing.JButton();
        JPanelBuscar = new javax.swing.JPanel();
        BBuscar = new javax.swing.JButton();
        tfNombreBU = new javax.swing.JTextField();
        tfTelefonoBU = new javax.swing.JTextField();
        JTelefono3 = new javax.swing.JLabel();
        JDNI3 = new javax.swing.JLabel();
        tfDNIBU = new javax.swing.JTextField();
        JNombre3 = new javax.swing.JLabel();
        JPanelModificar = new javax.swing.JPanel();
        BModificar = new javax.swing.JButton();
        tfTelefonoM = new javax.swing.JTextField();
        JTelefono4 = new javax.swing.JLabel();
        JDNI4 = new javax.swing.JLabel();
        tfDNIM = new javax.swing.JTextField();
        JNombre4 = new javax.swing.JLabel();
        tfNombreM = new javax.swing.JTextField();
        JNombre4_1 = new javax.swing.JLabel();
        tfNombreM1 = new javax.swing.JTextField();
        JTelefonoNuevo4 = new javax.swing.JLabel();
        tfTelefonoM1 = new javax.swing.JTextField();
        JNuevo1 = new javax.swing.JLabel();
        JNuevo2 = new javax.swing.JLabel();
        BValidar4 = new javax.swing.JButton();
        JModificado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 380));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 46, 131));
        jLabel1.setText("CLIENTES");

        JPanelAñadir.setBackground(new java.awt.Color(255, 255, 255));
        JPanelAñadir.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    AÑADIR CLIENTE    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelAñadir.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JPanelAñadir.setPreferredSize(new java.awt.Dimension(600, 207));

        JNombre1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNombre1.setForeground(new java.awt.Color(0, 0, 0));
        JNombre1.setText("Nombre:");

        tfNombre.setBackground(new java.awt.Color(255, 255, 255));
        tfNombre.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(0, 0, 0));
        tfNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombre.setCaretColor(new java.awt.Color(51, 51, 51));
        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreFocusLost(evt);
            }
        });

        JDNI1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JDNI1.setForeground(new java.awt.Color(0, 0, 0));
        JDNI1.setText("DNI:");

        BAñadir.setBackground(new java.awt.Color(255, 255, 255));
        BAñadir.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BAñadir.setForeground(new java.awt.Color(181, 46, 131));
        BAñadir.setText("AÑADIR");
        BAñadir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAñadir.setEnabled(false);
        BAñadir.setFocusPainted(false);
        BAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAñadirActionPerformed(evt);
            }
        });

        tfDNI.setBackground(new java.awt.Color(255, 255, 255));
        tfDNI.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfDNI.setForeground(new java.awt.Color(0, 0, 0));
        tfDNI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfDNI.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDNIFocusLost(evt);
            }
        });

        tfTelefono.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefono.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfTelefono.setForeground(new java.awt.Color(0, 0, 0));
        tfTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfTelefono.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefonoFocusLost(evt);
            }
        });

        JTelefono1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JTelefono1.setForeground(new java.awt.Color(0, 0, 0));
        JTelefono1.setText("Telefono:");

        JExiste.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        JExiste.setForeground(new java.awt.Color(255, 0, 0));
        JExiste.setText("El cliente ya existe");

        BNuevo.setBackground(new java.awt.Color(255, 255, 255));
        BNuevo.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        BNuevo.setForeground(new java.awt.Color(0, 0, 0));
        BNuevo.setText("X");
        BNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });

        BValidar1.setBackground(new java.awt.Color(255, 255, 255));
        BValidar1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BValidar1.setForeground(new java.awt.Color(181, 46, 131));
        BValidar1.setText("VALIDAR");
        BValidar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BValidar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BValidar1.setFocusPainted(false);
        BValidar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValidar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelAñadirLayout = new javax.swing.GroupLayout(JPanelAñadir);
        JPanelAñadir.setLayout(JPanelAñadirLayout);
        JPanelAñadirLayout.setHorizontalGroup(
            JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAñadirLayout.createSequentialGroup()
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelAñadirLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(JPanelAñadirLayout.createSequentialGroup()
                                .addComponent(JNombre1)
                                .addGap(18, 18, 18)
                                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelAñadirLayout.createSequentialGroup()
                                .addComponent(JDNI1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JTelefono1)
                                .addGap(0, 0, 0)
                                .addComponent(tfTelefono))))
                    .addGroup(JPanelAñadirLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPanelAñadirLayout.createSequentialGroup()
                                .addComponent(BValidar1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelAñadirLayout.createSequentialGroup()
                                .addComponent(JExiste)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelAñadirLayout.setVerticalGroup(
            JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAñadirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNombre1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTelefono1))
                    .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JDNI1)))
                .addGap(18, 18, 18)
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BValidar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JExiste)
                    .addComponent(BNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BAtras.setBackground(new java.awt.Color(0, 0, 0));
        BAtras.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        BAtras.setForeground(new java.awt.Color(255, 255, 255));
        BAtras.setText("ATRÁS");
        BAtras.setFocusPainted(false);
        BAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAtrasActionPerformed(evt);
            }
        });

        JPanelBorrar.setBackground(new java.awt.Color(255, 255, 255));
        JPanelBorrar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    BORRAR CLIENTE    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelBorrar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JPanelBorrar.setPreferredSize(new java.awt.Dimension(600, 182));

        JDNI2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JDNI2.setForeground(new java.awt.Color(0, 0, 0));
        JDNI2.setText("DNI:");

        tfDNIB.setBackground(new java.awt.Color(255, 255, 255));
        tfDNIB.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfDNIB.setForeground(new java.awt.Color(0, 0, 0));
        tfDNIB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfDNIB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDNIBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDNIBFocusLost(evt);
            }
        });

        BBorrar.setBackground(new java.awt.Color(255, 255, 255));
        BBorrar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BBorrar.setForeground(new java.awt.Color(181, 46, 131));
        BBorrar.setText("BORRAR");
        BBorrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BBorrar.setEnabled(false);
        BBorrar.setFocusPainted(false);
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        JBorrado.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        JBorrado.setForeground(new java.awt.Color(255, 0, 0));
        JBorrado.setText("El cliente ha sido borrado");

        BValidar2.setBackground(new java.awt.Color(255, 255, 255));
        BValidar2.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BValidar2.setForeground(new java.awt.Color(181, 46, 131));
        BValidar2.setText("VALIDAR");
        BValidar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BValidar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BValidar2.setFocusPainted(false);
        BValidar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValidar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelBorrarLayout = new javax.swing.GroupLayout(JPanelBorrar);
        JPanelBorrar.setLayout(JPanelBorrarLayout);
        JPanelBorrarLayout.setHorizontalGroup(
            JPanelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBorrarLayout.createSequentialGroup()
                .addGroup(JPanelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelBorrarLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(BValidar2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelBorrarLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(JBorrado)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelBorrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JDNI2)
                .addGap(18, 18, 18)
                .addComponent(tfDNIB, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        JPanelBorrarLayout.setVerticalGroup(
            JPanelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBorrarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(JBorrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDNIB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDNI2))
                .addGap(24, 24, 24)
                .addGroup(JPanelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BValidar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        JPanelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        JPanelBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    BUSCAR CLIENTE    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelBuscar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        BBuscar.setBackground(new java.awt.Color(255, 255, 255));
        BBuscar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BBuscar.setForeground(new java.awt.Color(181, 46, 131));
        BBuscar.setText("BUSCAR");
        BBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BBuscar.setEnabled(false);
        BBuscar.setFocusPainted(false);
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        tfNombreBU.setBackground(new java.awt.Color(255, 255, 255));
        tfNombreBU.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombreBU.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreBU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombreBU.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfNombreBU.setEnabled(false);

        tfTelefonoBU.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefonoBU.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfTelefonoBU.setForeground(new java.awt.Color(0, 0, 0));
        tfTelefonoBU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfTelefonoBU.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfTelefonoBU.setEnabled(false);

        JTelefono3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JTelefono3.setForeground(new java.awt.Color(0, 0, 0));
        JTelefono3.setText("Telefono:");

        JDNI3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JDNI3.setForeground(new java.awt.Color(0, 0, 0));
        JDNI3.setText("DNI:");

        tfDNIBU.setBackground(new java.awt.Color(255, 255, 255));
        tfDNIBU.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfDNIBU.setForeground(new java.awt.Color(0, 0, 0));
        tfDNIBU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfDNIBU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDNIBUFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDNIBUFocusLost(evt);
            }
        });

        JNombre3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNombre3.setForeground(new java.awt.Color(0, 0, 0));
        JNombre3.setText("Nombre:");

        javax.swing.GroupLayout JPanelBuscarLayout = new javax.swing.GroupLayout(JPanelBuscar);
        JPanelBuscar.setLayout(JPanelBuscarLayout);
        JPanelBuscarLayout.setHorizontalGroup(
            JPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBuscarLayout.createSequentialGroup()
                .addGroup(JPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JPanelBuscarLayout.createSequentialGroup()
                            .addComponent(JNombre3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfNombreBU, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JTelefono3)
                            .addGap(6, 6, 6)
                            .addComponent(tfTelefonoBU, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelBuscarLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(tfDNIBU, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelBuscarLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(JDNI3))))
                    .addGroup(JPanelBuscarLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        JPanelBuscarLayout.setVerticalGroup(
            JPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBuscarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(JPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDNIBU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDNI3))
                .addGap(18, 18, 18)
                .addGroup(JPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreBU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefonoBU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNombre3)
                    .addComponent(JTelefono3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        JPanelModificar.setBackground(new java.awt.Color(255, 255, 255));
        JPanelModificar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "    MODIFICAR CLIENTE    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Unispace", 0, 14), new java.awt.Color(181, 46, 131))); // NOI18N
        JPanelModificar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JPanelModificar.setPreferredSize(new java.awt.Dimension(600, 205));

        BModificar.setBackground(new java.awt.Color(255, 255, 255));
        BModificar.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BModificar.setForeground(new java.awt.Color(181, 46, 131));
        BModificar.setText("MODIFICAR");
        BModificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BModificar.setEnabled(false);
        BModificar.setFocusPainted(false);
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });

        tfTelefonoM.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefonoM.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfTelefonoM.setForeground(new java.awt.Color(0, 0, 0));
        tfTelefonoM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfTelefonoM.setCaretColor(new java.awt.Color(51, 51, 51));
        tfTelefonoM.setEnabled(false);

        JTelefono4.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JTelefono4.setForeground(new java.awt.Color(0, 0, 0));
        JTelefono4.setText("Telefono:");

        JDNI4.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JDNI4.setForeground(new java.awt.Color(0, 0, 0));
        JDNI4.setText("DNI:");

        tfDNIM.setBackground(new java.awt.Color(255, 255, 255));
        tfDNIM.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfDNIM.setForeground(new java.awt.Color(0, 0, 0));
        tfDNIM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfDNIM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDNIMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDNIMFocusLost(evt);
            }
        });

        JNombre4.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNombre4.setForeground(new java.awt.Color(0, 0, 0));
        JNombre4.setText("Nombre:");

        tfNombreM.setBackground(new java.awt.Color(255, 255, 255));
        tfNombreM.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombreM.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombreM.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tfNombreM.setEnabled(false);

        JNombre4_1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNombre4_1.setForeground(new java.awt.Color(0, 0, 0));
        JNombre4_1.setText("Nombre");

        tfNombreM1.setBackground(new java.awt.Color(255, 255, 255));
        tfNombreM1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfNombreM1.setForeground(new java.awt.Color(0, 0, 0));
        tfNombreM1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfNombreM1.setEnabled(false);

        JTelefonoNuevo4.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JTelefonoNuevo4.setForeground(new java.awt.Color(0, 0, 0));
        JTelefonoNuevo4.setText("Telefono");

        tfTelefonoM1.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefonoM1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tfTelefonoM1.setForeground(new java.awt.Color(0, 0, 0));
        tfTelefonoM1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfTelefonoM1.setEnabled(false);

        JNuevo1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNuevo1.setForeground(new java.awt.Color(0, 0, 0));
        JNuevo1.setText("nuevo:");

        JNuevo2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        JNuevo2.setForeground(new java.awt.Color(0, 0, 0));
        JNuevo2.setText("nuevo:");

        BValidar4.setBackground(new java.awt.Color(255, 255, 255));
        BValidar4.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        BValidar4.setForeground(new java.awt.Color(181, 46, 131));
        BValidar4.setText("VALIDAR");
        BValidar4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        BValidar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BValidar4.setFocusPainted(false);
        BValidar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValidar4ActionPerformed(evt);
            }
        });

        JModificado.setFont(new java.awt.Font("Unispace", 1, 12)); // NOI18N
        JModificado.setForeground(new java.awt.Color(255, 0, 0));
        JModificado.setText("El cliente ha sido modificado");

        javax.swing.GroupLayout JPanelModificarLayout = new javax.swing.GroupLayout(JPanelModificar);
        JPanelModificar.setLayout(JPanelModificarLayout);
        JPanelModificarLayout.setHorizontalGroup(
            JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelModificarLayout.createSequentialGroup()
                .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelModificarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelModificarLayout.createSequentialGroup()
                                .addComponent(JNombre4)
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelModificarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JDNI4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JNombre4_1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(JPanelModificarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JNuevo1)))
                .addGap(18, 18, 18)
                .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPanelModificarLayout.createSequentialGroup()
                            .addComponent(tfNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JTelefono4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JPanelModificarLayout.createSequentialGroup()
                            .addComponent(tfNombreM1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JTelefonoNuevo4)
                                .addComponent(JNuevo2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfTelefonoM1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelModificarLayout.createSequentialGroup()
                            .addComponent(BValidar4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156)))
                    .addGroup(JPanelModificarLayout.createSequentialGroup()
                        .addComponent(tfDNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(JModificado)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        JPanelModificarLayout.setVerticalGroup(
            JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelModificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDNI4)
                    .addComponent(JModificado))
                .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelModificarLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTelefono4)
                            .addComponent(tfTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNombreM1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelModificarLayout.createSequentialGroup()
                                .addComponent(JTelefonoNuevo4)
                                .addGap(25, 25, 25)
                                .addGroup(JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BValidar4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JNuevo2)
                                .addComponent(tfTelefonoM1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JPanelModificarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JNombre4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JNombre4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JPanelModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JPanelAñadir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPanelBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPanelBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(BAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(JPanelAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAñadirActionPerformed
      
        try {
            Proyecto.altaCliente(tfDNI.getText(),tfNombre.getText(),tfTelefono.getText());
            tfNombre.setText("");
            tfDNI.setText("");
            tfTelefono.setText("");
            tfDNI.setForeground(Color.black);
            
            
            
        } catch (Exception e) {
           System.out.println("No se ha podido insertar" + e.getClass());
        }
        
    }//GEN-LAST:event_BAñadirActionPerformed

    private void BAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAtrasActionPerformed
        Proyecto.cerrarVenatanaClientes();
    }//GEN-LAST:event_BAtrasActionPerformed

    private void tfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusLost
        consultarNombre();
        BValidar1.setEnabled(true);
    }//GEN-LAST:event_tfNombreFocusLost

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        JExiste.setVisible(false);
        BNuevo.setVisible(false);
        BAñadir.setVisible(true);
        BValidar1.setVisible(true);
        tfNombre.setEnabled(true);
        tfNombre.setText("");
        tfDNI.setEnabled(true);
        tfDNI.setText("");
        tfTelefono.setEnabled(true);
        tfTelefono.setText("");
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
          
        try {
            
            boolean existe =  Proyecto.borrarClientePorDNI(tfDNIB.getText());
           
            if(existe)
            {
              tfDNIB.setText("");  
              JBorrado.setVisible(true);
              tfDNIB.setForeground(Color.black);
            }
            else{
                tfDNIB.setText("No encontrado");
                tfDNIB.setForeground(Color.red);
            }
            
        } catch (Exception e) {
            System.out.println(e.getClass());
        }        
    }//GEN-LAST:event_BBorrarActionPerformed

    private void tfDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDNIFocusLost
        consultarDni(tfDNI,BAñadir);
        BAñadir.setEnabled(false);
    }//GEN-LAST:event_tfDNIFocusLost

    private void tfDNIBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDNIBFocusGained
        tfDNIB.setForeground(Color.black);
    }//GEN-LAST:event_tfDNIBFocusGained

    private void tfDNIBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDNIBFocusLost
        
    }//GEN-LAST:event_tfDNIBFocusLost

    private void tfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusGained
        tfNombre.setForeground(Color.black);
    }//GEN-LAST:event_tfNombreFocusGained

    private void tfTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoFocusGained
        tfDNIB.setText("");
        tfDNIB.setForeground(Color.black);
        BAñadir.setEnabled(false);
    }//GEN-LAST:event_tfTelefonoFocusGained

    private void tfTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefonoFocusLost
        consultarTelefono();
    }//GEN-LAST:event_tfTelefonoFocusLost

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        contadorBuscarModificar = 1;
        buscarCliente();
    }//GEN-LAST:event_BBuscarActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
        ModificarCliente();
    }//GEN-LAST:event_BModificarActionPerformed

    private void tfDNIBUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDNIBUFocusGained
        tfDNIBU.setText("");
        tfDNIBU.setForeground(Color.black);
        tfNombreBU.setText("");
        tfTelefonoBU.setText("");
        BBuscar.setEnabled(true);
    }//GEN-LAST:event_tfDNIBUFocusGained

    private void tfDNIBUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDNIBUFocusLost
        consultarDni(tfDNIBU,BBuscar);
    }//GEN-LAST:event_tfDNIBUFocusLost

    private void tfDNIMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDNIMFocusGained
        tfNombreM.setText("");
        JModificado.setVisible(false);
        tfNombreM1.setEnabled(false);
        tfTelefonoM1.setEnabled(false);
        tfDNIM.setForeground(Color.black);
    }//GEN-LAST:event_tfDNIMFocusGained

    private void tfDNIMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDNIMFocusLost
        
    }//GEN-LAST:event_tfDNIMFocusLost

    private void BValidar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValidar1ActionPerformed
        consultarDni(tfDNI,BAñadir);
        consultarTelefono();
        consultarNombre();
        consultaDNI(tfDNI);
        if(contadorAñadir1==1 && contadorAñadir2==1 && contadorAñadir3==1){
            BAñadir.setEnabled(true);
            contadorAñadir1=0;
            contadorAñadir2=0;
            contadorAñadir3=0;
            
        }
    }//GEN-LAST:event_BValidar1ActionPerformed

    private void BValidar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValidar2ActionPerformed
        try {
            consultarDni(tfDNIB, BBorrar);
            boolean validarDni = validarDni(tfDNIB.getText());
                if(validarDni){
                    tfDNIB.setForeground(Color.green);
                    BBorrar.setEnabled(true);
                }
                else{
                    tfDNIB.setForeground(Color.red);
                    BBorrar.setEnabled(false);
                }
                    
        } catch (Exception e) {
            Logger.getLogger(VentanaClientes.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_BValidar2ActionPerformed

    private void BValidar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValidar4ActionPerformed
        try {
            consultarDni(tfDNIM, BModificar);
            boolean existe = buscarCliente();
            if(existe){
                tfNombreM1.setEnabled(true);
                tfTelefonoM1.setEnabled(true);
            }
            else{
                tfNombreM1.setEnabled(false);
                tfTelefonoM1.setEnabled(false);
            }
            
            boolean validarNombre = validarNombre(tfNombreM1);
            if(validarNombre){
                tfNombreM1.setForeground(Color.green);
            }
            else{
                tfNombreM1.setForeground(Color.red);
            }
            
            boolean validarTelefono = validarTelefono(tfTelefonoM1);
            if(validarTelefono){
                tfTelefonoM1.setForeground(Color.green);
            }
            else{
                tfTelefonoM1.setForeground(Color.red);
            }
            
            if(existe && validarNombre && validarTelefono){
                BModificar.setEnabled(true);
            }
            else{
                BModificar.setEnabled(false);
            }
            
            
        } catch (Exception e) {
            System.out.println(e.getClass());
        }
        
        
        
    }//GEN-LAST:event_BValidar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaClientes().setVisible(true);
            }
        });
    }
    
    private void consultaDNI(JTextField DNI){
        try{
            encontrado = Proyecto.buscarClientePorDNI(DNI.getText());
           if (encontrado)
           {
               // Persona encontrada
               personaEncontrada();
           }
           else
           {
               // Persona nueva
               personaNueva();
           }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       }
    }
    
   
    private void personaEncontrada() throws Exception{
        
        JExiste.setVisible(true);
        BNuevo.setVisible(true);
        BAñadir.setVisible(false);
        BValidar1.setVisible(false);
       
        tfNombre.setEnabled(false);
        tfDNI.setEnabled(false);
        tfTelefono.setEnabled(false);
         // Datos del cliente
        tfNombre.setText(Proyecto.getNombreCliente());
        tfDNI.setText(Proyecto.getDNICliente());
        tfTelefono.setText(Proyecto.getTelefonoCliente());
                
    }
    
    private void personaNueva() throws Exception{
        JExiste.setVisible(false);
        BNuevo.setVisible(false);
        tfNombre.setEnabled(true);
        tfDNI.setEnabled(true);
        tfTelefono.setEnabled(true);
    }
    
    private void consultarDni(JTextField DNI, JButton Boton){
        try{
          boolean correcto = validarDni(DNI.getText());
          contadorAñadir1=0;
           if (correcto)
           {
               
               DNI.setForeground(Color.green);
               contadorAñadir1++;
           }
           else
           {
               DNI.setForeground(Color.red);
               Boton.setEnabled(false);
           }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       }
    }
    
    private boolean validarDni(String DNI) throws Exception{
        String dnipat = "^\\d{8}[A-HJ-NP-TV-Z]$";
        if (Pattern.matches(dnipat, DNI)== false ){
            return false;
        }
        else{
            return true;
        }
    }
    
    private void consultarNombre(){
        try{
          boolean correcto = validarNombre(tfNombre);
          contadorAñadir2=0;
           if (correcto)
           {
               tfNombre.setForeground(Color.green);
               contadorAñadir2++;
           }
           else
           {
               tfNombre.setForeground(Color.red);
               BAñadir.setEnabled(false);
           }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       }
    }
    
    private boolean validarNombre(JTextField Nombre) throws Exception{
        String nombrepat = "^[A-zÑñ\\s]{1,25}$";
        if (Pattern.matches(nombrepat, Nombre.getText())== false ){
            return false;
        }
        else{
            return true;
        }
    }
    
     private void consultarTelefono(){
        try{
          boolean correcto = validarTelefono(tfTelefono);
          contadorAñadir3=0;
           if (correcto)
           {
               tfTelefono.setForeground(Color.green);
               contadorAñadir3++;
           }
           else
           {
               tfTelefono.setForeground(Color.red);
               BAñadir.setEnabled(false);
           }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       }
    }
    
    private boolean validarTelefono(JTextField Telefono) throws Exception{
        String telefonopat = "^\\d{9}$";
        if (Pattern.matches(telefonopat, Telefono.getText())== false ){
            return false;
        }
        else{
            return true;
        }
    }
    
    private boolean buscarCliente(){
        try{
                if(contadorBuscarModificar==1){
                    encontrado = Proyecto.buscarClientePorDNI(tfDNIBU.getText());
                    if (encontrado)
                        {
                            tfNombreBU.setText(Proyecto.getNombreCliente());
                            tfTelefonoBU.setText(Proyecto.getTelefonoCliente());
                        }
                        else
                        {
                            tfDNIBU.setForeground(Color.red);
                            tfDNIBU.setText("No existe");
                            BBuscar.setEnabled(false);
                        }
                }
                else{
                    encontrado = Proyecto.buscarClientePorDNI(tfDNIM.getText());
                    
                    if (encontrado)
                        {
                            tfNombreM.setText(Proyecto.getNombreCliente());
                            tfTelefonoM.setText(Proyecto.getTelefonoCliente());
                            return true;
                        }
                        else
                        {
                            tfDNIM.setForeground(Color.red);
                            tfDNIM.setText("No existe");
                        }
                }
       }
       catch(Exception e){
           System.out.println(e.getClass());
       }
        
        return false;
    }
    
    private void ModificarCliente(){
       boolean modificado;
        try {
            
            modificado = Proyecto.modificarCliente(tfDNIM.getText(),tfNombreM1.getText(),tfTelefonoM1.getText());
            if(modificado){
                   JModificado.setVisible(true);
            }
            
            tfNombreM.setText("");
            tfDNIM.setText("");
            tfTelefonoM.setText("");
            tfNombreM1.setText("");
            tfTelefonoM1.setText("");
            tfDNIM.setForeground(Color.black);
            tfNombreM1.setForeground(Color.black);
            tfTelefonoM1.setForeground(Color.black);
            
            
            
            
        } catch (Exception e) {
            System.out.println("No se ha podido insertar" + e.getClass());
        }
        
        
        
    }
        
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAtras;
    private javax.swing.JButton BAñadir;
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BModificar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BValidar1;
    private javax.swing.JButton BValidar2;
    private javax.swing.JButton BValidar4;
    private javax.swing.JLabel JBorrado;
    private javax.swing.JLabel JDNI1;
    private javax.swing.JLabel JDNI2;
    private javax.swing.JLabel JDNI3;
    private javax.swing.JLabel JDNI4;
    private javax.swing.JLabel JExiste;
    private javax.swing.JLabel JModificado;
    private javax.swing.JLabel JNombre1;
    private javax.swing.JLabel JNombre3;
    private javax.swing.JLabel JNombre4;
    private javax.swing.JLabel JNombre4_1;
    private javax.swing.JLabel JNuevo1;
    private javax.swing.JLabel JNuevo2;
    private javax.swing.JPanel JPanelAñadir;
    private javax.swing.JPanel JPanelBorrar;
    private javax.swing.JPanel JPanelBuscar;
    private javax.swing.JPanel JPanelModificar;
    private javax.swing.JLabel JTelefono1;
    private javax.swing.JLabel JTelefono3;
    private javax.swing.JLabel JTelefono4;
    private javax.swing.JLabel JTelefonoNuevo4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfDNIB;
    private javax.swing.JTextField tfDNIBU;
    private javax.swing.JTextField tfDNIM;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreBU;
    private javax.swing.JTextField tfNombreM;
    private javax.swing.JTextField tfNombreM1;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfTelefonoBU;
    private javax.swing.JTextField tfTelefonoM;
    private javax.swing.JTextField tfTelefonoM1;
    // End of variables declaration//GEN-END:variables
}
