/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import main.Proyecto;

/**
 *
 * @author victor
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BSalir = new javax.swing.JButton();
        BPedido = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        JPlatos = new javax.swing.JMenu();
        JPAñadir = new javax.swing.JMenuItem();
        JPModificarU = new javax.swing.JMenuItem();
        JPBorrar = new javax.swing.JMenuItem();
        JPModificarN = new javax.swing.JMenuItem();
        JClientes = new javax.swing.JMenu();
        JCAñadir = new javax.swing.JMenuItem();
        JCBorrar = new javax.swing.JMenuItem();
        JCBuscar = new javax.swing.JMenuItem();
        JCModificar = new javax.swing.JMenuItem();
        JEstadisticas = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/egibide.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 46, 131));
        jLabel1.setText("ESCUELA DE HOSTELERIA");

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(181, 46, 131));
        jLabel3.setText("EGIBIDE-MENDIZORROTZA");

        jLabel2.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(181, 46, 131));
        jLabel2.setText("DE");

        BSalir.setBackground(new java.awt.Color(0, 0, 0));
        BSalir.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        BSalir.setForeground(new java.awt.Color(255, 255, 255));
        BSalir.setText("SALIR");
        BSalir.setFocusPainted(false);
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        BPedido.setBackground(new java.awt.Color(0, 0, 0));
        BPedido.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        BPedido.setForeground(new java.awt.Color(255, 255, 255));
        BPedido.setText("PEDIDO");
        BPedido.setFocusPainted(false);
        BPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPedidoActionPerformed(evt);
            }
        });

        JPlatos.setText("PLATOS");
        JPlatos.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        JPAñadir.setText("Añadir plato");
        JPAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPAñadirActionPerformed(evt);
            }
        });
        JPlatos.add(JPAñadir);

        JPModificarU.setText("Modificar unidades");
        JPModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPModificarUActionPerformed(evt);
            }
        });
        JPlatos.add(JPModificarU);

        JPBorrar.setText("Borrar plato");
        JPBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPBorrarActionPerformed(evt);
            }
        });
        JPlatos.add(JPBorrar);

        JPModificarN.setText("Modificar nombre");
        JPModificarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPModificarNActionPerformed(evt);
            }
        });
        JPlatos.add(JPModificarN);

        jMenuBar.add(JPlatos);

        JClientes.setText("CLIENTES");
        JClientes.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N

        JCAñadir.setText("Añadir cliente");
        JCAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCAñadirActionPerformed(evt);
            }
        });
        JClientes.add(JCAñadir);

        JCBorrar.setText("Borrar cliente");
        JCBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBorrarActionPerformed(evt);
            }
        });
        JClientes.add(JCBorrar);

        JCBuscar.setText("Buscar Cliente");
        JCBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBuscarActionPerformed(evt);
            }
        });
        JClientes.add(JCBuscar);

        JCModificar.setText("Modificar Cliente");
        JCModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCModificarActionPerformed(evt);
            }
        });
        JClientes.add(JCModificar);

        jMenuBar.add(JClientes);

        JEstadisticas.setText("ESTADISTICAS");
        JEstadisticas.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        JEstadisticas.setMargin(new java.awt.Insets(5, 10, 2, 10));

        jMenuItem5.setText("Clientes");
        JEstadisticas.add(jMenuItem5);

        jMenuItem8.setText(" Platos");
        JEstadisticas.add(jMenuItem8);

        jMenuItem6.setText("Pedidos");
        JEstadisticas.add(jMenuItem6);

        jMenuBar.add(JEstadisticas);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(Logo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(BPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Logo)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        Proyecto.terminar();
    }//GEN-LAST:event_BSalirActionPerformed

    private void BPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPedidoActionPerformed
        Proyecto.pedido();
    }//GEN-LAST:event_BPedidoActionPerformed

    private void JPAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPAñadirActionPerformed
        Proyecto.añadirPlato();
    }//GEN-LAST:event_JPAñadirActionPerformed

    private void JPModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPModificarUActionPerformed
        Proyecto.modificarUnidadesPlato();
    }//GEN-LAST:event_JPModificarUActionPerformed

    private void JCAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCAñadirActionPerformed
        Proyecto.añadirCliente();
    }//GEN-LAST:event_JCAñadirActionPerformed

    private void JCBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBorrarActionPerformed
        Proyecto.borrarCliente();
    }//GEN-LAST:event_JCBorrarActionPerformed

    private void JCBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBuscarActionPerformed
        Proyecto.buscarCliente();
    }//GEN-LAST:event_JCBuscarActionPerformed

    private void JCModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCModificarActionPerformed
        Proyecto.modificarCliente();
    }//GEN-LAST:event_JCModificarActionPerformed

    private void JPModificarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPModificarNActionPerformed
        Proyecto.cambiarNombrePlato();
    }//GEN-LAST:event_JPModificarNActionPerformed

    private void JPBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPBorrarActionPerformed
        Proyecto.borrarPlato();
    }//GEN-LAST:event_JPBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPedido;
    private javax.swing.JButton BSalir;
    private javax.swing.JMenuItem JCAñadir;
    private javax.swing.JMenuItem JCBorrar;
    private javax.swing.JMenuItem JCBuscar;
    private javax.swing.JMenuItem JCModificar;
    private javax.swing.JMenu JClientes;
    private javax.swing.JMenu JEstadisticas;
    private javax.swing.JMenuItem JPAñadir;
    private javax.swing.JMenuItem JPBorrar;
    private javax.swing.JMenuItem JPModificarN;
    private javax.swing.JMenuItem JPModificarU;
    private javax.swing.JMenu JPlatos;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
