/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaejer3;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 1gdaw07
 */
public class V2Ejer3 extends javax.swing.JFrame {

    /**
     * Creates new form V2Ejer3
     */
    public V2Ejer3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAceptar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        JLApellido = new javax.swing.JLabel();
        JLDNI = new javax.swing.JLabel();
        TfProducto = new javax.swing.JTextField();
        TfUnidades = new javax.swing.JTextField();
        TfImporte = new javax.swing.JTextField();
        bCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        BotonAceptar.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        BotonSalir.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel1.setText("VENTANA VENTAS");

        JLNombre.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        JLNombre.setText("Producto");

        JLApellido.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        JLApellido.setText("Unidades");

        JLDNI.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        JLDNI.setText("Importe");

        TfProducto.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        TfProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfProductoActionPerformed(evt);
            }
        });

        TfUnidades.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        TfUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfUnidadesActionPerformed(evt);
            }
        });

        TfImporte.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        TfImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfImporteActionPerformed(evt);
            }
        });

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(BotonAceptar)
                .addGap(58, 58, 58)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bCalcular))
                            .addComponent(TfUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLApellido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLDNI)
                    .addComponent(bCalcular))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAceptar)
                    .addComponent(BotonSalir))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        // TODO add your handling code here:

        int correcto = 0;
        int contador = 0;

        String producto = TfProducto.getText();
        Pattern pat1 = Pattern.compile("^[A-Z\\sa-z]+$");
        Matcher mat1 = pat1.matcher(producto);
        if (mat1.matches ()){
            JavaEjer3.validarProducto(producto);
            correcto++;
            contador++;
        }

        if(producto.isEmpty() || correcto==0){
            TfProducto.setBackground(Color.red);
            TfProducto.setText("");
        }
        else {
            TfProducto.setText(producto);
            TfProducto.setBackground(Color.GREEN);
        }

        correcto = 0;

        String unidades = TfUnidades.getText();
        Pattern pat2 = Pattern.compile("^[0-9]{1,3}$");
        Matcher mat2 = pat2.matcher(unidades);
        if (mat2.matches ()){
            JavaEjer3.validarUnidades(unidades);
            correcto++;
            contador++;
        }

        if(unidades.isEmpty() || correcto==0){
            TfUnidades.setBackground(Color.RED);
            TfUnidades.setText("");
        }
        else {
            TfUnidades.setText(unidades);
            TfUnidades.setBackground(Color.GREEN);
        }

        correcto = 0;

        String importe = TfImporte.getText();

        Pattern pat = Pattern.compile("^[0-9]{1,2}.[0-9]{2}$");
        Matcher mat = pat.matcher(importe);
        if (mat.matches ()){
            JavaEjer3.validarImporte(importe);
            correcto++;
            contador++;
        }
        if(importe.isEmpty() || correcto==0){
            TfImporte.setBackground(Color.RED);
            TfImporte.setText("");
        }
        else {
            TfImporte.setText(importe);
            TfImporte.setBackground(Color.GREEN);
        }

        if(contador==3){
            JavaEjer3.GuardarProducto();
            TfProducto.setText("");
            TfUnidades.setText("");
            TfImporte.setText("");

            TfProducto.setBackground(Color.WHITE);
            TfUnidades.setBackground(Color.WHITE);
            TfImporte.setBackground(Color.WHITE);

            JOptionPane.showMessageDialog(null, "Producto añadido correctamente");
        }

    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        JavaEjer3.MenuV1();

    }//GEN-LAST:event_BotonSalirActionPerformed

    private void TfProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfProductoActionPerformed
        // TODO add your handling code here;

    }//GEN-LAST:event_TfProductoActionPerformed

    private void TfUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfUnidadesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TfUnidadesActionPerformed

    private void TfImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfImporteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TfImporteActionPerformed

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        if (tfProducto.getText().isEmpty() || tfProducto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Datos erroneos!");
        } else {
            if (Main.buscarProducto(tfProducto.getText())) {
                String precio = Main.buscarPrecioUnitario(tfProducto.getText());
                tfImporte.setText(Integer.toString(Integer.parseInt(precio) * Integer.parseInt(tfUnidades.getText())));
                calculo = true;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Producto no encontrado en la base de datos!");
                calculo = false;
            }
        }
    }//GEN-LAST:event_bCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V2Ejer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V2Ejer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V2Ejer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V2Ejer3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V2Ejer3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel JLApellido;
    private javax.swing.JLabel JLDNI;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JTextField TfImporte;
    private javax.swing.JTextField TfProducto;
    private javax.swing.JTextField TfUnidades;
    private javax.swing.JButton bCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
