/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaejer2;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 1gdaw07
 */
public class VEjer2 extends javax.swing.JFrame {
    
    

    /**
     * Creates new form VEjer2
     */
    public VEjer2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JLNombre = new javax.swing.JLabel();
        JLApellido = new javax.swing.JLabel();
        JLDNI = new javax.swing.JLabel();
        TfNombre = new javax.swing.JTextField();
        TfApellido = new javax.swing.JTextField();
        TfDni = new javax.swing.JTextField();
        BotonAceptar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel1.setText("ALTA PERSONAS");

        JLNombre.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        JLNombre.setText("Nombre");

        JLApellido.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        JLApellido.setText("Apellidos");

        JLDNI.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        JLDNI.setText("DNI");

        TfNombre.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        TfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNombreActionPerformed(evt);
            }
        });

        TfApellido.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        TfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfApellidoActionPerformed(evt);
            }
        });

        TfDni.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        TfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfDniActionPerformed(evt);
            }
        });

        BotonAceptar.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        BotonSalir.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLNombre)
                            .addComponent(JLDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BotonAceptar)
                        .addGap(78, 78, 78)
                        .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNombre)
                    .addComponent(TfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLApellido)
                    .addComponent(TfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDNI)
                    .addComponent(TfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAceptar)
                    .addComponent(BotonSalir))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNombreActionPerformed
        // TODO add your handling code here; 
       
    }//GEN-LAST:event_TfNombreActionPerformed

    private void TfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfApellidoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TfApellidoActionPerformed

    private void TfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfDniActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TfDniActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        // TODO add your handling code here:
        
        int correcto = 0; 
        int contador = 0;
        
        String nombre = TfNombre.getText(); 
        Pattern pat1 = Pattern.compile("^[A-Z\\sa-z]+$");
        Matcher mat1 = pat1.matcher(nombre);
        if (mat1.matches ()){
            JavaEjer2.validarNombre(nombre);
            correcto++;
            contador++;
        }
        
        if(nombre.isEmpty() || correcto==0){
            TfNombre.setBackground(Color.RED);
            TfApellido.setText("");
        }
        else {
            TfNombre.setText(nombre);
            TfNombre.setBackground(Color.GREEN);
        }
        
        correcto = 0; 
        
        
        String apellido = TfApellido.getText();
        Pattern pat2 = Pattern.compile("^[A-Z\\sa-z]+$");
        Matcher mat2 = pat2.matcher(apellido);
        JavaEjer2.validarApellido(apellido);
        if (mat2.matches ()){
            JavaEjer2.validarApellido(apellido);
            correcto++;
            contador++;
        }
        
        if(apellido.isEmpty() || correcto==0){
            TfApellido.setBackground(Color.RED);
            TfApellido.setText("");
        }
        else {
            TfApellido.setText(apellido);
            TfApellido.setBackground(Color.GREEN);
        }
        
        correcto = 0; 
                
        String DNI = TfDni.getText();
        
        Pattern pat = Pattern.compile("^[0-9]{8}[A-Z]$");
        Matcher mat = pat.matcher(DNI);
        JavaEjer2.validarDni(DNI);
        
        if (mat.matches ()){
            JavaEjer2.validarDni(DNI);
            correcto++;
            contador++;
        }
        if(DNI.isEmpty() || correcto==0){
            TfDni.setBackground(Color.RED);
            TfDni.setText("");
        }
        else {
            TfDni.setText(DNI);
            TfDni.setBackground(Color.GREEN);
        }
        
        
       
        
        if(contador==3){
             JavaEjer2.GuardarPersona();
             TfNombre.setText("");
        TfApellido.setText("");
        TfDni.setText("");
        
        TfNombre.setBackground(Color.WHITE);
        TfApellido.setBackground(Color.WHITE);
        TfDni.setBackground(Color.WHITE);
        
        JOptionPane.showMessageDialog(null, "Persona añadida correctamente");
        }
        
    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        JavaEjer2.MostrarV2();
        
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEjer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEjer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEjer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEjer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEjer2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel JLApellido;
    private javax.swing.JLabel JLDNI;
    private javax.swing.JLabel JLNombre;
    private javax.swing.JTextField TfApellido;
    private javax.swing.JTextField TfDni;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
